# OCP Version

ocp_version_maj: "4"
ocp_version_min: "4.16"
ocp_version_patch: "4.16.0"

# Base file locations for the playbook, must be writable to the user running ansible-playbook
base_dir: /home/kni/ocp-ansible
bin_dir: /home/kni/ocp-ansible/bin
config_dir: /home/kni/ocp-ansible/config
build_dir: /home/kni/ocp-ansible/build
iso_tmp_dir: "{{base_dir}}"
build_dir: "{{base_dir}}"

# provisioner host settings
provisioner_host_packages:
  - httpd
  - tmux
  - git
  - genisoimage
  - xorriso
  - podman
  - syslinux
  - git
  - libvirt
  - python3-libvirt
  - python3-lxml
  - qemu-kvm
  - mkisofs
  - python3-devel
  - jq
  - runc
  - ipmitool
  - dhcp-client

provisioner_host_services:
  - httpd

isolinux_files:
  - vesamenu.c32
  - isolinux.bin
  - ldlinux.c32
  - libcom32.c32

provisioner_host: 172.18.42.211
provisioner_host_ilo: "{{ provisioner_host }}"
provisioner_http_scheme: http
provisioner_http_port: 80
provisioner_host_container_runtime: podman

coreos_installer_image: "quay.io/coreos/coreos-installer:release"
fcct_image: "quay.io/coreos/fcct:release"


# General cluster settings
cluster_name: ocp
base_domain: jpmchase.com
fips_mode: false
provisioner_ssh_public_key: "REDACTED"

# HTTP Proxy Settings
proxy_enabled: false
proxy_url: http://172.18.11.25:3128
no_proxy: "172.18.0.0/16,172.31.0.0/16"
tls_additional_cas: []
# - |
#   -----BEGIN CERTIFICATE-----
#   PEM-format CA cert goes here
#   -----END CERTIFICATE-----

# Node provisioning settings, may be overwritten in host_vars per-node
wipe_disks: true
verify_ilo_serial_number: true
ilo_pad_serial: true
deploy_disk: sda

# Cluster Network Settings
transpile_nic_configs: false
domain_name: jpmchase.com
fallback_dns: 172.18.42.10
nameservers:
  - 172.18.42.10
  - 172.18.42.11

sdn_settings:
  ipsec_enabled: true
customize_network_operator_config: true

# Openshift Sources and Pull Secret
source_urls:
  installer: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-{{ ocp_version_min }}/openshift-install-linux.tar.gz
  client: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-{{ ocp_version_min }}/openshift-client-linux.tar.gz
  mirror_registry: https://mirror.openshift.com/pub/openshift-v4/clients/mirror-registry/latest/mirror-registry.tar.gz

  rhcos_kernel: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/{{ ocp_version_min }}/latest/rhcos-live-kernel-x86_64
  rhcos_initrd: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/{{ ocp_version_min }}/latest/rhcos-live-initramfs.x86_64.img
  rhcos_image: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ ocp_version_min }}/latest/rhcos-live-rootfs.x86_64.img

# Pull secret may be added to secret.yml instead, comment out if moved.
pull_secret: 'REDACTED'

# Do not edit, overwrite in host_vars as needed
interfaces: []
bonds: []
