role: worker
boot_if: ens192
standalone_interfaces: ['ens192']
interfaces:
  - name: ens192
    ip_address: 172.18.0.71
    ip_netmask: 255.255.255.0
    gateway: 172.18.0.1
pm_type: vmware
deploy_disk: sda
short_name: ocp2-worker-2
